
const initialDetails = [
    {
      id: 1,
      imgPath: "/assets/img/1.png",
      name: "Jane Doe",
      email: "janedoe@gmail.com",
      address: "New Delhi, India",
      crime: "No Crimes Committed",
      ghcard: "GHA-12323434-1",
    },
    {
      id: 2,
      imgPath: "/assets/img/2.png",
      name: "Mary Rosamund",
      email: "agra@rosie.com",
      address: "Tbilisi, India",
      crime: "Fraud",
      ghcard: "GHA-364772638-1",
    },
    {
      id: 3,
      imgPath: "/assets/img/3.png",
      name: "Sherlock Watson",
      email: "irene@johnlock.com",
      crime: "No Crimes Committed",
      address: "Baker Street, India",
      ghcard: "GHA-527372834-1",
    },
    {
      id: 4,
      imgPath: "/assets/img/4.png",
      name: "John Holmes",
      email: "mary@johnlock.com",
      address: "Baker Street, India",
      crime: "Rape",
      ghcard: "GHA-745377238-1",
    },
    {
      id: 5,
      imgPath: "/assets/img/5.png",
      name: "Mycroft Lestrade",
      email: "britishgovt@gmail.com",
      address: "London, India",
      crime: "Rape",
      ghcard: "GHA-9862736382-1",
    },
    {
        id: 6,
        imgPath: "/assets/img/1.png",
        name: "Samuel Doae",
        email: "janedoe@gmail.com",
        address: "New Delhi, India",
        crime: "No Crimes Committed",
        ghcard: "GHA-8692837-1",
      },
      {
        id: 7,
        imgPath: "/assets/img/2.png",
        name: "Mary Ankrah",
        email: "agra@rosie.com",
        address: "Tbilisi, India",
        crime: "No Crimes Committed",
        ghcard: "GHA-6875847-1",
      },
      {
        id: 8,
        imgPath: "/assets/img/3.png",
        name: "James Watson",
        email: "irene@johnlock.com",
        address: "Baker Street, India",
        crime: "Kidnapping",
      },
      {
        id: 9,
        imgPath: "/assets/img/4.png",
        name: "Akosua Asantewaa",
        email: "mary@johnlock.com",
        crime: "No Crimes Committed",
        address: "Baker Street, India",
      },
      {
        id: 10,
        imgPath: "/assets/img/5.png",
        name: "Asante Williams",
        email: "britishgovt@gmail.com",
        address: "London, India",
        crime: "Robbery and Murder",
      },
      {
        id: 11,
        imgPath: "/assets/img/1.png",
        name: "Rauf Abubakar",
        email: "janedoe@gmail.com",
        address: "New Delhi, India",
        crime: "No Crimes Committed",
      },
      {
        id: 12,
        imgPath: "/assets/img/2.png",
        name: "Razak Bihu",
        email: "agra@rosie.com",
        address: "Tbilisi, India",
        crime: "Fraud",
      },
      {
        id: 13,
        imgPath: "/assets/img/3.png",
        name: "Patrick Adjei",
        email: "irene@johnlock.com",
        crime: "No Crimes Committed",
        address: "Baker Street, India",
      },
      {
        id: 14,
        imgPath: "/assets/img/4.png",
        name: "John Koomson",
        email: "mary@johnlock.com",
        address: "Baker Street, India",
        crime: "Rape",
      },
      {
        id: 15,
        imgPath: "/assets/img/5.png",
        name: "Gergina Bentum",
        email: "britishgovt@gmail.com",
        address: "London, India",
        crime: "Rape",
      },
      {
          id: 16,
          imgPath: "/assets/img/1.png",
          name: "George Ansong",
          email: "janedoe@gmail.com",
          address: "New Delhi, India",
          crime: "No Crimes Committed"
        },
        {
          id:17,
          imgPath: "/assets/img/2.png",
          name: "Beatrice Kessewaa",
          email: "agra@rosie.com",
          address: "Tbilisi, India",
          crime: "No Crimes Committed",
        },
        {
          id: 18,
          imgPath: "/assets/img/3.png",
          name: "Diana Ama",
          email: "irene@johnlock.com",
          address: "Baker Street, India",
          crime: "Kidnapping",
        },
        {
          id: 19,
          imgPath: "/assets/img/4.png",
          name: "Abigail Kudjoe",
          email: "mary@johnlock.com",
          crime: "No Crimes Committed",
          address: "Baker Street, India",
        },
        {
          id: 20,
          imgPath: "/assets/img/5.png",
          name: "Kojo Fosu",
          email: "britishgovt@gmail.com",
          address: "London, India",
          crime: "Robbery and Murder",
        },
  ];
  
  export default initialDetails;